language: python
python:
- '2.7'
- '3.5'
- '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
sudo: false
cache: pip
install:
- pip install tox-travis
script: tox -v
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/django-dbtemplates/upload
  distributions: sdist bdist_wheel
  password:
    secure: xDkRgaRI29FIVfQ5WEj6zSIlbBdFK/BE2RYQpSggVeTpUaZucS2RtE7it2hCMMYU5patHbcGJtw/DKGMtAhhZcm9tYCpn7cyW6vyF7tT385mbk5yggdjz5MoIHjQJD9NW1fqFRwLIJPICy6U6apxvQ1SpVtF13Dfu5AaCMv4cvk=
  on:
    tags: true
    repo: jazzband/django-dbtemplates
    python: 3.7
